name: vconsol-axios-lib

on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        node:
          - 16
          - 18
          - 20
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ matrix.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-
      - run: npm install
      - run: npm run test
